외부 내부 상관관계 측정

In [36]:
import pandas as pd
import csv
import matplotlib.pyplot as plt
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
import numpy as np

In [42]:
df = pd.read_csv('feeds.csv', encoding='cp949')

In [38]:
df.head()

        created_at  entry_id  온도  CO2   습도  pm1  pm2.5  pm10  외부pm10   co
0  2019-05-20 5:00         7  24   42  467    3      6     8      36  0.4
1  2019-05-20 6:00        10  23   48  469    2      2     3      52  0.3
2  2019-05-20 7:00        13  24   47  595    1      2     3      38  0.3
3  2019-05-20 8:00        25  24   49  962    1      2     2      48  0.3
4  2019-05-20 9:00        38  24   46  804    1      3     4      60  0.3

In [43]:
df = df.iloc[:, 2:]

In [46]:
df = df.replace("-", np.nan)
df['co'] = df['co'].astype(str).astype(float)

In [48]:
df.corr()

,온도,CO2,습도,pm1,pm2.5,pm10,외부pm10,co
온도,1.000000,0.184712,0.389884,-0.114279,-0.018795,-0.116566,-0.194699,0.174642
CO2,0.184712,1.000000,0.502177,0.047346,0.371420,0.229732,0.367154,0.371052
습도,0.389884,0.502177,1.000000,0.038991,-0.296838,-0.368405,0.111411,0.161259
pm1,-0.114279,0.047346,0.038991,1.000000,0.031581,-0.001062,0.237405,0.094751
pm2.5,-0.018795,0.371420,-0.296838,0.031581,1.000000,0.856242,0.246279,0.437220
pm10,-0.116566,0.229732,-0.368405,-0.001062,0.856242,1.000000,0.219438,0.359270
외부pm10,-0.194699,0.367154,0.111411,0.237405,0.246279,0.219438,1.000000,0.297926
co,0.174642,0.371052,0.161259,0.094751,0.437220,0.359270,0.297926,1.000000